---
BuiltModuleSubDirectory: Module

####################################################
#       Sampler Pipeline Configuration             #
####################################################
# Defining 'Workflows' (suite of InvokeBuild tasks) to be run using their alias
BuildWorkflow:
  '.': # "." is the default Invoke-Build workflow. It is called when no -Tasks is specified to the build.ps1
    - build
    - pack
    - test

  build:
    - Clean
    - PowerShell5Compatibility
    - Build_Module_ModuleBuilder
    - LoadDatumConfigData
    - TestConfigData
    - CompileDatumRsop
    - TestReferenceRsop
    - Set_PSModulePath
    - TestDscResources
    - CompileRootConfiguration
    - CompileRootMetaMof

  pack:
    - PowerShell5Compatibility
    - LoadDatumConfigData
    - ConvertMofFilesToUnicode
    - NewMofChecksums
    - CompressModulesWithChecksum
    - Compress_Artifact_Collections
    - TestBuildAcceptance

  packguestconfiguration:
    - PowerShell5Compatibility
    - LoadDatumConfigData
    - NewMofChecksums
    - CompressModulesWithChecksum
    - Compress_Artifact_Collections
    - TestBuildAcceptance
    - build_guestconfiguration_packages_from_MOF
    - publish_guestconfiguration_packages

  rsop:
    - LoadDatumConfigData
    - CompileDatumRsop
    - TestDscResources

  publish:
    - publish_module_to_gallery
    - Publish_Release_To_GitHub
    - Create_ChangeLog_GitHub_PR

  hqrmtest:
    - Invoke_HQRM_Tests_Stop_On_Fail

  test:
    - Pester_Tests_Stop_On_Fail
    - Convert_Pester_Coverage
    - Pester_If_Code_Coverage_Under_Threshold

####################################################
#          Pester Configuration (Sampler)          #
####################################################
Pester:
  Configuration:
    Run:
      Path:
        - tests/QA
    Output:
      Verbosity: Detailed
      StackTraceVerbosity: Full
      CIFormat: Auto
    CodeCoverage:
      CoveragePercentTarget: 0
      OutputPath: JaCoCo_coverage.xml
      OutputEncoding: ascii
      UseBreakpoints: false
    TestResult:
      OutputFormat: NUnitXML
      OutputEncoding: ascii
  ExcludeFromCodeCoverage:

####################################################
#      Pester Configuration (DscResource.Test)     #
####################################################
DscTest:
  Pester:
    Configuration:
      Filter:
        ExcludeTag:
          - BuiltModule Tests - Validate Localization
      Output:
        Verbosity: Detailed
        CIFormat: Auto
      TestResult:
        OutputFormat: NUnitXML
        OutputEncoding: ascii
        OutputPath: ./output/testResults/NUnitXml_HQRM_Tests.xml
  Script:
    ExcludeSourceFile:
      - output
    ExcludeModuleFile:
      - DscWorkshop.psm1
    MainGitBranch: main

# Import ModuleBuilder tasks from a specific PowerShell module using the build
# task's alias. Wildcard * can be used to specify all tasks that has a similar
# prefix and or suffix. The module contain the task must be added as a required
# module in the file RequiredModules.psd1.
ModuleBuildTasks:
  Sampler:
    - '*.build.Sampler.ib.tasks'
  Sampler.DscPipeline:
    - '*.ib.tasks'
  Sampler.GitHubTasks:
    - '*.ib.tasks'
  Sampler.AzureDevOpsTasks:
    - 'Task.*'
  DscResource.DocGenerator:
    - 'Task.*'
  DscResource.Test:
    - 'Task.*'

# Invoke-Build Header to be used to 'decorate' the terminal output of the tasks.
TaskHeader: |
  param($Path)
  ""
  "=" * 79
  Write-Build Cyan "`t`t`t$($Task.Name.replace("_"," ").ToUpper())"
  Write-Build DarkGray  "$(Get-BuildSynopsis $Task)"
  "-" * 79
  Write-Build DarkGray "  $Path"
  Write-Build DarkGray "  $($Task.InvocationInfo.ScriptName):$($Task.InvocationInfo.ScriptLineNumber)"
  ""

Sampler.DscPipeline:
  DscCompositeResourceModules:
  - PSDesiredStateConfiguration
  - DscConfig.Demo
  #- Name: CommonTasks
  #  Version: 0.3.259

####################################################
#           Setting Sampler PSModulePath           #
####################################################
SetPSModulePath:
  RemovePersonal: true
  RemoveProgramFiles: true

####################################################
#               GitHub Configuration               #
####################################################
GitHubConfig:
  GitHubFilesToAdd:
    - 'CHANGELOG.md'
  GitHubConfigUserName: dscbot
  GitHubConfigUserEmail: dsccommunity@outlook.com
  UpdateChangelogOnPrerelease: false

####################################################
#             DscResource.DocGenerator             #
####################################################
DscResource.DocGenerator:
  Generate_Conceptual_Help:
    BuiltModuleSubdirectory: Module

####################################################
#                Git Configuration                 #
####################################################
GitConfig:
  UserName: dscbot
  UserEmail: dsccommunity@outlook.com

####################################################
#            Pull Request Configuration            #
####################################################
PullRequestConfig:
  BranchName: updateChangelogAfterv{0}
  Title: Updating Changelog since release of v{0} +semver:skip
  Description: Updating Changelog since release of v{0} +semver:skip
  Instance: dscdo01:8080
  Collection: AutomatedLab
  Project: DscConfig.Demo
  RepositoryID: DscConfig.Demo
  Debug: false
